# Generated by Django 5.0.4 on 2024-05-31 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=100)),
                ('license_num', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('textarea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('em_contact_name', models.CharField(max_length=100)),
                ('em_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
